name: Compilazione Tesi con GitHub Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
          use_biber: true

      - name: Carica il PDF generato
        uses: actions/upload-artifact@v4
        with:
          name: tesi-pdf
          path: main.pdf
