name: Compila Tesi con XeLaTeX e Biber

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clona il repository
        uses: actions/checkout@v4

      - name: Installa LaTeX completo con Biber
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full

      - name: Compila la tesi con latexmk
        run: |
          latexmk -xelatex -interaction=nonstopmode -file-line-error main.tex

      - name: Carica il PDF generato
        uses: actions/upload-artifact@v4
        with:
          name: tesi-pdf
          path: main.pdf
